language: python
python:
  - "3.3"
  - "nightly" # currently points to 3.6-dev
# command to install dependencies
install: 
  - pip install -r requirements.txt
  - pip install coveralls
# command to run tests
script: nosetests
after_success:
  coveralls
